version: '3'

services:
  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'quoridor_db'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'Bxu<!yGaY"tj={J7b3U[T],qm9Ms>^ZL'
    ports:
      - "3306:3306"
    volumes:
      - mysql_quoridor_db:/var/lib/mysql
    container_name: db
    networks:
      - backend
      - frontend

  quoridor-api:
    depends_on:
      - mysql
    working_dir: /app
    #command: bash -c "nodemon index.js" 
    #command: tail -F /dev/null
    command: bash -c "yarn add nodemon && yarn start"
    restart: unless-stopped
    image: node:latest
    ports:
      - 9696:8080
    volumes:
      - "./src/api:/app"
    environment:
      - DB_HOST=db
      - DB_USER=api
      - DB_PASSWORD=password
      - DB_NAME=quoridor_db
      - DB_PORT=3306
      # - CLIENT_ORIGIN=http://cs-devel.potsdam.edu:3000
    container_name: api
    networks:
      - backend
      - frontend

  quoridor-client:
    build: ./django
    depends_on:
      - quoridor-api
    restart: unless-stopped
    #user: "${HOST_USER_ID}:${HOST_GROUP_ID}"
    volumes:
      - ./src/client:/app
    working_dir: /app/quoridor_site
    #command: ["chmod -x /app/wait-for-it.sh","/app/wait-for-it.sh", "db:${DJANGO_PORT}", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    #command: tail -F /dev/null
    # ./migrate.sh &&  
    command: bash -c "./migrate.sh && python manage.py runserver 0.0.0.0:8000"

    container_name: web
    ports:
      - "8000:8000"
    networks:
      - frontend

volumes:
  mysql_quoridor_db:

networks:
  backend:
  frontend: