# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test01(self):
    # Test name: Test01
    # Step # | name | target | value
    # 1 | open | http://localhost:8000/user/ | 
    self.driver.get("http://localhost:8000/user/")
    # 2 | setWindowSize | 1200x761 | 
    self.driver.set_window_size(1200, 761)
    # 3 | click | css=h1 | 
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    # 4 | click | css=.flex-container | 
    self.driver.find_element(By.CSS_SELECTOR, ".flex-container").click()
    # 5 | click | css=a:nth-child(1) > .custom_button | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .custom_button").click()
    # 6 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 7 | click | linkText=Enter a Name | 
    self.driver.find_element(By.LINK_TEXT, "Enter a Name").click()
    # 8 | click | name=name | 
    self.driver.find_element(By.NAME, "name").click()
    # 9 | type | name=name | jackMurphy
    self.driver.find_element(By.NAME, "name").send_keys("jackMurphy")
    # 10 | type | name=name | Kyle
    self.driver.find_element(By.NAME, "name").send_keys("Kyle")
    # 11 | click | css=p:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    # 12 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 13 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
