# Generated by Django 4.0.3 on 2022-04-01 13:36

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor_site_backend', '0002_profile_delete_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
