# Generated by Django 4.0.3 on 2022-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor_site_backend', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name='losses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name='wins'),
        ),
    ]
