# Generated by Django 4.0.4 on 2022-05-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor_site_backend', '0009_game_players_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_set', to='quoridor_site_backend.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_set', to='quoridor_site_backend.profile'),
        ),
    ]
