# Generated by Django 4.0.4 on 2022-05-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor_site_backend', '0010_remove_game_players_game_player1_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_set', to='quoridor_site_backend.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_set', to='quoridor_site_backend.profile'),
        ),
    ]
