# Generated by Django 4.0.3 on 2022-05-19 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quoridor_site_backend', '0011_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(max_length=190, on_delete=django.db.models.deletion.CASCADE, related_name='player1_set', to='quoridor_site_backend.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(max_length=190, on_delete=django.db.models.deletion.CASCADE, related_name='player2_set', to='quoridor_site_backend.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
