import unittest

from api import *
#from client.api import *

# note, method names must start with 'test'
class TestGameEngine(unittest.TestCase):
    def test_new_game(self):
        board_should_be_html = """<div id='wrapper'><h1>Converted Game Board:</h1>      <section id='left'><table><tbody><tr><td style=''>a9</td><td style=''>b9</td><td style=''>c9</td><td style=''>d9</td><td style='background-color:#baffc9;'>e9</td><td style=''>f9</td><td style=''>g9</td><td style=''>h9</td><td style=''>i9</td></tr><tr><td style=''>a8</td><td style=''>b8</td><td style=''>c8</td><td style=''>d8</td><td style=''>e8</td><td style=''>f8</td><td style=''>g8</td><td style=''>h8</td><td style=''>i8</td></tr><tr><td style=''>a7</td><td style=''>b7</td><td style=''>c7</td><td style=''>d7</td><td style=''>e7</td><td style=''>f7</td><td style=''>g7</td><td style=''>h7</td><td style=''>i7</td></tr><tr><td style=''>a6</td><td style=''>b6</td><td style=''>c6</td><td style=''>d6</td><td style=''>e6</td><td style=''>f6</td><td style=''>g6</td><td style=''>h6</td><td style=''>i6</td></tr><tr><td style=''>a5</td><td style=''>b5</td><td style=''>c5</td><td style=''>d5</td><td style=''>e5</td><td style=''>f5</td><td style=''>g5</td><td style=''>h5</td><td style=''>i5</td></tr><tr><td style=''>a4</td><td style=''>b4</td><td style=''>c4</td><td style=''>d4</td><td style=''>e4</td><td style=''>f4</td><td style=''>g4</td><td style=''>h4</td><td style=''>i4</td></tr><tr><td style=''>a3</td><td style=''>b3</td><td style=''>c3</td><td style=''>d3</td><td style=''>e3</td><td style=''>f3</td><td style=''>g3</td><td style=''>h3</td><td style=''>i3</td></tr><tr><td style=''>a2</td><td style=''>b2</td><td style=''>c2</td><td style=''>d2</td><td style=''>e2</td><td style=''>f2</td><td style=''>g2</td><td style=''>h2</td><td style=''>i2</td></tr><tr><td style=''>a1</td><td style=''>b1</td><td style=''>c1</td><td style=''>d1</td><td style='background-color:#bae1ff;'>e1</td><td style=''>f1</td><td style=''>g1</td><td style=''>h1</td><td style=''>i1</td></tr></tbody></table></section><section id='right'><table>      <tr><td style = 'background-color:#bae1ff;'>Player 1</td><td style = 'background-color:#baffc9;'>Player 2</td></tr>      <tr><td style = 'background-color:#ffffba;'>Player 3</td><td style = 'background-color:#ffdfba;'>Player 4</td></tr>      </table></section>"""
        self.assertEqual(new_game().status_code, 200)
        self.assertEqual(new_game().text, board_should_be_html)
     
    def test_make_move(self):    
      board_should_be_html ="""<div id='wrapper'><h1>Converted Game Board:</h1>      <section id='left'><table><tbody><tr><td style=''>a9</td><td style=''>b9</td><td style=''>c9</td><td style=''>d9</td><td style='background-color:#baffc9;'>e9</td><td style=''>f9</td><td style=''>g9</td><td style=''>h9</td><td style=''>i9</td></tr><tr><td style=''>a8</td><td style=''>b8</td><td style=''>c8</td><td style=''>d8</td><td style=''>e8</td><td style=''>f8</td><td style=''>g8</td><td style=''>h8</td><td style=''>i8</td></tr><tr><td style=''>a7</td><td style=''>b7</td><td style=''>c7</td><td style=''>d7</td><td style=''>e7</td><td style=''>f7</td><td style=''>g7</td><td style=''>h7</td><td style=''>i7</td></tr><tr><td style=''>a6</td><td style=''>b6</td><td style=''>c6</td><td style=''>d6</td><td style=''>e6</td><td style=''>f6</td><td style=''>g6</td><td style=''>h6</td><td style=''>i6</td></tr><tr><td style=''>a5</td><td style=''>b5</td><td style=''>c5</td><td style=''>d5</td><td style=''>e5</td><td style=''>f5</td><td style=''>g5</td><td style=''>h5</td><td style=''>i5</td></tr><tr><td style=''>a4</td><td style=''>b4</td><td style=''>c4</td><td style=''>d4</td><td style=''>e4</td><td style=''>f4</td><td style=''>g4</td><td style=''>h4</td><td style=''>i4</td></tr><tr><td style=''>a3</td><td style=''>b3</td><td style=''>c3</td><td style=''>d3</td><td style=''>e3</td><td style=''>f3</td><td style=''>g3</td><td style=''>h3</td><td style=''>i3</td></tr><tr><td style=''>a2</td><td style=''>b2</td><td style=''>c2</td><td style=''>d2</td><td style='background-color:#bae1ff;'>e2</td><td style=''>f2</td><td style=''>g2</td><td style=''>h2</td><td style=''>i2</td></tr><tr><td style=''>a1</td><td style=''>b1</td><td style=''>c1</td><td style=''>d1</td><td style=''>e1</td><td style=''>f1</td><td style=''>g1</td><td style=''>h1</td><td style=''>i1</td></tr></tbody></table></section><section id='right'><table>      <tr><td style = 'background-color:#bae1ff;'>Player 1</td><td style = 'background-color:#baffc9;'>Player 2</td></tr>      <tr><td style = 'background-color:#ffffba;'>Player 3</td><td style = 'background-color:#ffdfba;'>Player 4</td></tr>      </table></section>"""
      response = make_move("e2","/ / e1 e9 / 10 10 / 1","1")
      self.assertEqual(response.status_code, 200)
      self.assertEqual(response.text, board_should_be_html)

        

if __name__ == "__main__":
  unittest.main()
